$(function(){var nav=$('.navbar'),navH;function bodyPad(){navH=nav.innerHeight();$('body.user-side').css('padding-top',navH);}
bodyPad();$(window).load(bodyPad);$(window).resize(bodyPad);});$(function(){var scene=document.getElementById('hero-parallax'),scene2=document.getElementById('floating-bullets');if($(scene2).length){var parallax2=new Parallax(scene2);}});(function($){var modalWrap=$('.modal-wrap'),modalTrigger=$('.modal-trigger'),modalClose=modalWrap.find('.close'),container=$('.modal-inner-content');var iOS=!!navigator.platform&&/iPad|iPhone|iPod/.test(navigator.platform);function modalToggle(e){e.preventDefault();var el=$(this),modalLink=el.attr('href').split('#')[1],modalTarget=$('#'+modalLink+'');if(modalTarget.hasClass('modal-show')){modalTarget.css('opacity','0');setTimeout(function(){modalTarget.removeClass('modal-show');},150);$('body').removeClass('disable-scroll');if(iOS){var offset=parseInt(document.body.style.top,10);document.body.classList.remove('modal--opened');document.body.scrollTop=(offset*-1);}}else{if(iOS){var offset=document.body.scrollTop;document.body.style.top=(offset*-1)+'px';document.body.classList.add('modal--opened');}
modalTarget.addClass('modal-show');setTimeout(function(){modalTarget.css('opacity','1');},10);$('body').addClass('disable-scroll');}}
modalWrap.click(function(e){var el=$(this);if(!container.is(e.target)&&container.has(e.target).length===0){el.css('opacity','0');setTimeout(function(){el.removeClass('modal-show');},150);$('body').removeClass('disable-scroll');if(iOS){var offset=parseInt(document.body.style.top,10);document.body.classList.remove('modal--opened');document.body.scrollTop=(offset*-1);}}});function modalOff(e){e.preventDefault();$(this).parents('.modal-wrap').css('opacity','0');setTimeout(function(){$(this).parents('.modal-wrap').removeClass('modal-show');},150);$('body').removeClass('disable-scroll');if(iOS){var offset=parseInt(document.body.style.top,10);document.body.classList.remove('modal--opened');document.body.scrollTop=(offset*-1);}}
modalTrigger.click(modalToggle);modalClose.click(modalOff);modalWrap.find('.modal-trigger').click(modalOff);})(jQuery);$(function(){var target=$('.scroll-fade-out'),range,hero=$('.hero');if(hero.length){$(window).resize(function(){rangeCheck();});rangeCheck();$(window).on('scroll',function(){var scrollTop=$(this).scrollTop();var offset=hero.offset().top;var height=hero.outerHeight();offset=offset+height/2;var calc=1-(scrollTop-offset+range)/range;target.css({'opacity':calc});if(calc>'1'){target.css({'opacity':1});}else if(calc<'0'){target.css({'opacity':0});}});function rangeCheck(){if($(window).width()<=768){range=200;}else{range=300;}}}});$(function(){var sidebar=$('.sidebar'),content=$('.main-content'),sidebarTrigger=$('.sidebar-toggle');function sidebarToggle(e){e.preventDefault();var el=$(this);if(sidebar.hasClass('sidebar-slide')){sidebar.removeClass('sidebar-slide');content.removeClass('sidebar-open');}else{content.addClass('sidebar-open');sidebar.addClass('sidebar-slide');}}
sidebarTrigger.click(sidebarToggle);});$(function(){var elem=$('.datepicker');if(elem.length)
elem.datepicker();});$(function(){var form=$('.advanced-multiselect-search'),formInput=$('.multisearch-input'),dropdownResults=$('.multisearch-suggestions'),selectResult=$('.select-result'),selectChoice=$('.select-choice');form.each(function(){var el=$(this);el.find(formInput).on('click',function(){dropdownResults.hide();el.find(dropdownResults).show();el.find('.search-field input').focus();});el.find(selectResult).click(function(){selectChoice=$('<li class="select-choice" />').insertBefore(el.find('.search-field'));selectChoice.html($(this).text()+'<span class="close"></span>');el.find(selectChoice).find('.close').click(function(){$(this).parent().remove();$(this).show();});});});$(document).click(function(e){var container=formInput;if(!container.is(e.target)&&container.has(e.target).length===0){form.find(dropdownResults).hide();}});});$(function(){var body=$('body');function initContent(){body.removeClass('not--loaded');body.addClass('is--loaded');setTimeout(function(){body.removeClass('is--loaded')},1600);}
$(window).load(initContent);});$(function(){var owl1=$('.owl-module');if(owl1.length){owl1.owlCarousel({autoplay:true,autoplayTimeout:3000,items:5,loop:true,nav:true,autoplayHoverPause:true,mouseDrag:false,navText:'',margin:10,responsive:{0:{items:1},480:{items:1},1024:{items:4},1280:{items:5}}});}});$(function(){var navTrigger=$('.nav-menu'),closeMenu,scaleTimeout,reset,el;function toggleMenu(){if($(window).width()>=768){navTrigger.off();navTrigger.hover(function(){el=$(this);clearTimeout(reset);navTrigger.removeClass('fade-out-menu open-menu fade-in-menu');el.addClass('open-menu');scaleTimeout=setTimeout(function(){el.addClass('fade-in-menu');},50);clearTimeout(closeMenu);},function(){closeMenu=setTimeout(function(){navTrigger.addClass('fade-out-menu');reset=setTimeout(function(){navTrigger.removeClass('fade-out-menu open-menu fade-in-menu');},250);},300);});}else{navTrigger.off();navTrigger.click(function(){el=$(this);if(!navTrigger.hasClass('open-menu')){el.addClass('open-menu');}else{el.removeClass('open-menu');}});}}
toggleMenu();$(window).resize(toggleMenu);});function validate(evt){var theEvent=evt||window.event;var key=theEvent.keyCode||theEvent.which;key=String.fromCharCode(key);var regex=/[0-9]|\./;if(!regex.test(key)){theEvent.returnValue=false;if(theEvent.preventDefault)theEvent.preventDefault();}}
$(function(){var btn=$('.btn-site'),sites=$('.sites'),template=$('<input type="text" class="form-control" />');if(sites.length>1){$('.remove-site').addClass('show');}else{$('.remove-site').removeClass('show');}
function addRemove(e){e.preventDefault();var el=$(this);if(el.hasClass('add-site')){template.clone().appendTo(sites);}
if(el.hasClass('remove-site')){sites.children().last().remove();}
if(sites.children().length>1){$('.remove-site').addClass('show');}else{$('.remove-site').removeClass('show');}}
btn.click(addRemove);});$(function(){$('[data-toggle="tooltip"]').tooltip({html:true});});$(function(){var elem=$(".device-tracking-chart-legend>li>a");function hoverChart(e){var el=$(this);$(el.data('target')).trigger(e.type);}
elem.on('mouseenter mouseleave',hoverChart);});$(function(){var section=$('.main-content-section-inner');function heightFix(){var navH=$('.navbar').innerHeight(),footerH=$('footer').innerHeight();section.css('min-height',$(window).height()-(navH+footerH+30));}
heightFix();$(window).resize(heightFix);});$(function(){var elem=$('.custom-datatable');if(elem.length){elem.DataTable({iDisplayLength:25,responsive:true,order:[[$('th.sorting_desc').index(),'desc']]});}
var elem2=$('.table-legend');if(elem2.length){elem2.DataTable({iDisplayLength:25,paging:false,ordering:false,info:false,responsive:true});resizeTable();$(window).resize(resizeTable);}
function resizeTable(){var wH=elem2.parents('div[class*=col-md]').width();setTimeout(function(){elem2.css('width',wH);},150);}});$(function(){var UniqueRandom={NumHistory:new Array(),generate:function(maxNum){var current=Math.round(Math.random()*(maxNum-1));if(maxNum>1&&this.NumHistory.length>0){if(this.NumHistory.length!=maxNum){while($.inArray(current,this.NumHistory)!=-1){current=Math.round(Math.random()*(maxNum-1));}
this.NumHistory.push(current);return current;}else{return current;}}else{this.NumHistory.push(current);return current;}}};$('.expandable-collapse').each(function(){var randomnumber=UniqueRandom.generate($('.expandable-item').length);$(this).attr('id','faq-'+randomnumber);var answerID=$(this).attr('id');$(this).prev().attr('data-target','#'+answerID);});});$(function(){$('.blogNav a').each(function(){var text=$(this).find('.blogNav-title').text();if($(this).find('.blogNav-title').html().length>10){text=text.substr(0,10)+'...';$(this).find('.blogNav-title').text(text);}});});$(function(){var $element=$('.rotate');if($element.length){$element.textrotator({animation:"flipUp",separator:",",speed:2000});}});$(function(){if($('#particles-js').length){particlesJS.load('particles-js','/templates/js/particles.json',function(){});}});$('body').on('click','input, textarea',function(){$('body').on('focusout','.focus-hide',function(){if($(this).val().length===0){$(this).next('label').show();}});});$('body').on('change','input, textarea',function(){if($(this).val().length>0){$(this).addClass('field-filled');}else{$(this).removeClass('field-filled');}});$('input, textarea').each(function(){if($(this).val().length>0){$(this).addClass('field-filled');}else{$(this).removeClass('field-filled');}});$('body').on('click','.menu-item',function(e){if($(this).parent().hasClass('active')){$(this).parent().removeClass('active');$(this).find('.fa-caret-down').removeClass('fa-caret-down').addClass('fa-caret-right');}else{$(this).parent().addClass('active');$(this).find('.fa-caret-right').removeClass('fa-caret-right').addClass('fa-caret-down');}});$('.has-submenu.active').each(function(){$(this).find('.fa-caret-right').addClass('fa-caret-down').removeClass('fa-caret-right');});$('.menu_holder_display').click(function(){$('.menu_holder').toggle();});